// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmE5ecsJAdikT_-mk1idpeqoF9R_laGzw',
    appId: '1:611444805102:web:0ddc5bedb11fc62f2ad2ff',
    messagingSenderId: '611444805102',
    projectId: 'mat-practice-pte',
    authDomain: 'mat-practice-pte.firebaseapp.com',
    databaseURL: 'https://mat-practice-pte-default-rtdb.firebaseio.com',
    storageBucket: 'mat-practice-pte.appspot.com',
    measurementId: 'G-8P17SSC7YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD24basv3nYcu2lag7PfK-4_OOXPz_6CQ8',
    appId: '1:611444805102:android:d56cf5b0804e44132ad2ff',
    messagingSenderId: '611444805102',
    projectId: 'mat-practice-pte',
    databaseURL: 'https://mat-practice-pte-default-rtdb.firebaseio.com',
    storageBucket: 'mat-practice-pte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxraJgAgrvOCoidtgBT5NCcfpNdSA7DM',
    appId: '1:611444805102:ios:28056ebb499590872ad2ff',
    messagingSenderId: '611444805102',
    projectId: 'mat-practice-pte',
    databaseURL: 'https://mat-practice-pte-default-rtdb.firebaseio.com',
    storageBucket: 'mat-practice-pte.appspot.com',
    androidClientId: '611444805102-caik8rfvaslvd9g883flmc0c5q3s969j.apps.googleusercontent.com',
    iosClientId: '611444805102-a5v73h9n82jipidsho71j571rogn3d9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.matPraticePte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxraJgAgrvOCoidtgBT5NCcfpNdSA7DM',
    appId: '1:611444805102:ios:28056ebb499590872ad2ff',
    messagingSenderId: '611444805102',
    projectId: 'mat-practice-pte',
    databaseURL: 'https://mat-practice-pte-default-rtdb.firebaseio.com',
    storageBucket: 'mat-practice-pte.appspot.com',
    androidClientId: '611444805102-caik8rfvaslvd9g883flmc0c5q3s969j.apps.googleusercontent.com',
    iosClientId: '611444805102-a5v73h9n82jipidsho71j571rogn3d9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.matPraticePte',
  );
}
